DownloaderForReddit/GUI/DownloaderForRedditGUI.py
DownloaderForReddit/GUI/DownloaderForRedditSettingsGUI.py
DownloaderForReddit/GUI/ImgurClientDialog.py
DownloaderForReddit/GUI_Resources/ImgurClientDialog.ui
DownloaderForReddit/GUI_Resources/ImgurClientDialog_auto.py
DownloaderForReddit/Persistence/SettingsManager.py
DownloaderForReddit/Utils/ImgurUtils.py

Imgur has a commercial API endpoint at [https://rapidapi.com/imgur/api/imgur-9](https://rapidapi.com/imgur/api/imgur-9) which does not have any rate limits.

Implemented support for Imgur's commercial API endpoint. 

---

DownloaderForReddit/Extractors/ImgurExtractor.py

Fixed various bugs in the ImgurExtractor

ImgurExtractor bug fixes

---

DownloaderForReddit/GUI/DownloaderForRedditGUI.py
DownloaderForReddit/GUI/RedditObjectSettingsDialog.py
DownloaderForReddit/Utils/ImgurUtils.py

Resolves Issue #74

---

DownloaderForReddit/Extractors/ImgurExtractor.py
Tests/UnitTests/Extractors/test_ImgurExtractor.py

`ImgurExtractor` now passes all unit tests.

Fixed ImgurExtractor unit test fails

---

build.spec

The provided spec file for building is now fully ready to build, so long as developers are using virtualenv.

Fully Automated pyinstaller spec

---

DownloaderForReddit/GUI/FailedDownloadsDialog.py
DownloaderForReddit/Utils/Exporters/XMLExporter.py

Various bug fixes with FailedDownloadDialog

Download failed fix

---

.gitignore

Gitignore file sourced from Gitignore file sourced from https://github.com/github/gitignore/blob/master/Python.gitignore

Added standard python gitignore

---

DownloaderForReddit/Utils/Exporters/JsonExporter.py
DownloaderForReddit/Utils/Exporters/TextExporter.py
DownloaderForReddit/Utils/Exporters/XMLExporter.py

Test post:
https://www.reddit.com/r/dfr_tests/comments/elp3m4/test_post/

Fixed UnicodeEncodeError when exporting posts with Unicode titles

---

.github/workflows/Build.yml
.github/workflows/Test.yml

Based on my testing, this speeds up the github Actions run by a factor of 2

GitHub cache

---

DownloaderForReddit/Extractors/GfycatExtractor.py

redgifs is gfycat's NSFW version. It's backend is stillg gfycat

Added redgifs to gfycat url keys

---

DownloaderForReddit/Core/Content.py
DownloaderForReddit/Extractors/RedditVideoExtractor.py
DownloaderForReddit/Utils/SystemUtil.py
DownloaderForReddit/Utils/VideoMerger.py

Fixes the first part of issue #94 in which the date modified was not changed for video files that were merged.

Video date modified fix

---

DownloaderForReddit/Utils/VideoMerger.py

Fixes logging errors in VideoMerger and unhandled exception when trying to delete video part file that no longer exists.

Video merger fix

---

DownloaderForReddit/Core/DownloadRunner.py
DownloaderForReddit/GUI/DownloaderForRedditGUI.py

Fixes #100, crashing due to a certain key word in a user/subreddits name.

Output crash fix

---

DownloaderForReddit/Extractors/GfycatExtractor.py

Redgifs has split their API endpoint from gfycat. See https://www.reddit.com/r/redgifs/comments/gf2a97/api_access/fqwnpdc/

New Redgifs endpoint

---

CHANGE_LOG.md
DownloaderForReddit/core/download_runner.py
DownloaderForReddit/core/submission_handler.py
DownloaderForReddit/database/__init__.py
DownloaderForReddit/database/models.py
DownloaderForReddit/extractors/base_extractor.py
DownloaderForReddit/extractors/reddit_uploads_extractor.py
DownloaderForReddit/extractors/reddit_video_extractor.py
DownloaderForReddit/gui/message_dialogs.py
DownloaderForReddit/gui/settings/supported_video_settings_widget.py
DownloaderForReddit/gui/widgets/object_settings_widget.py
DownloaderForReddit/messaging/message.py
DownloaderForReddit/utils/imgur_utils.py
DownloaderForReddit/utils/system_util.py
DownloaderForReddit/utils/token_parser.py
DownloaderForReddit/utils/video_merger.py
DownloaderForReddit/viewmodels/reddit_object_list_model.py
Tests/unittests/core/test_submission_handler.py
Tests/unittests/extractors/test_reddit_video_extractor.py
Tests/unittests/utils/test_system_utils.py

Update to fix several issues from v3.1.1-beta.

Database backend

---

CHANGE_LOG.md
DownloaderForReddit/version.py
Resources/supported_video_sites.txt
requirements.txt

Update youtube-dl and add supported site url for youtu.be

---

.github/workflows/Build.yml

This seems to clear the antivirus issue. (Issue #234)
https://www.virustotal.com/gui/file/59b627f9b2694e5de0a11432abf4b9507f60d1e326747358cf49517089b63944?nocache=1

Bumped python version used for building to 3.8

---

CHANGE_LOG.md
DownloaderForReddit/version.py

Release version for recent upgrades to build process.
Fixes #234

Increase version and update change log

---

CHANGE_LOG.md
DownloaderForReddit/core/downloader.py
DownloaderForReddit/extractors/erome_extractor.py
DownloaderForReddit/version.py

Fix erome extraction and download

---

CHANGE_LOG.md
DownloaderForReddit/utils/reddit_utils.py
DownloaderForReddit/version.py

Fix exception handling in check_authorized_connection method

---

DownloaderForReddit/core/const.py
DownloaderForReddit/core/downloader.py
DownloaderForReddit/extractors/__init__.py
DownloaderForReddit/extractors/gfycat_extractor.py
DownloaderForReddit/extractors/redgifs_extractor.py
Tests/mockobjects/mock_objects.py
Tests/unittests/extractors/test_gfycat_extractor.py
Tests/unittests/extractors/test_redgifs_extractor.py

Adds a separate extractor for redgifs since they updated their api.
Fixes #298

Fix redgifs extraction

---

DownloaderForReddit/database/models.py
DownloaderForReddit/gui/export_wizard.py
DownloaderForReddit/utils/general_utils.py
DownloaderForReddit/utils/token_parser.py

Fix datetime display

---

DownloaderForReddit/gui/downloader_for_reddit_gui.py

Fix crash on context menu open without available list

---

DownloaderForReddit/extractors/redgifs_extractor.py
requirements.txt

Fix redgifs for a third time

---

.gitpod.Dockerfile
.gitpod.yml

Updated the Dockerfile to compose a docker container that works out of the box for working with this app

Gitpod Setup

---

DownloaderForReddit/gui/database_views/database_dialog.py
requirements.txt

359 fix download dialog crash

---

DownloaderForReddit/core/download/downloader.py

Fix #365 - Deleted content placeholder images being downloaded.

Add minimum download size limit to avoid deleted content placeholders
