DownloaderForReddit/Extractors/ImgurExtractor.py
I discovered that the Imgur API will occasionally append an extraneous ?1 query to the end of the URL for images in an album. 
This commit handles this case.
=> Added handling of URL 

DownloaderForReddit/Extractors/GfycatExtractor.py, Tests/MockObjects/MockObjects.py, Tests/UnitTests/Extractors/test_GfycatExtractor.py
Gfycat URLs can have tags in them in the form 
`https://gfycat.com/[gfyid]-[tag1]-[tag2]-[tag3]-...`
This pull request handles these tagged URLs.
=> Added support for Gfycat tagged URLs

DownloaderForReddit/GUI/DownloaderForRedditGUI.py
Running the download_single option when a download is already running would cause DFR to crash.
=> Fixed Bug causing Crash

DownloaderForReddit/Core/DownloadRunner.py, DownloaderForReddit/Core/PostFilter.py, Tests/MockObjects/MockObjects.py, Tests/UnitTests/Core/test_DownloadRunner.py
Rework the method to extract praw submissions from the praw submission generator.
The old method had to take in every submission from the praw submission generator, then exclude submissions by date.  For previously downloaded users with long post histories this, could be a very time consuming task made unnecessary if only a few new posts had been made since last download.
This rework uses the generator more efficiently to increase the extraction speed.  After each submission is yielded from the generator, the submission date is checked, and if the date is out of the acceptable range the generator iteration is broken and the application proceeds with the next step.
In some tests this sped extraction up by as much as 85%.
=> Praw submission extractor rework

DownloaderForReddit/GUI/DownloaderForRedditSettingsGUI.py
On Windows, `QtCore.QThread.idealThreadCount()` simply returns the number of logical cores on your computer. However, downloading things is an IO-bound, not CPU bound task. In particular, it is limited by the TCP bandwidth-delay-product, which is why download accelerators demonstrate a speedup with multi-threaded downloading. 
In my experiments, I found that increasing the number of threads from 8 to 64 beyond the number of CPU cores increased my mid-extraction bandwidth utilization from 60 Mbps to 99.5 Mbps on a 100 Mbps Ethernet connection when downloading from Eurome.
=> Decoupled thread count from number of cores

requirements.txt
This resolves a bug where DFR crashes when you re-open a RedditObjectSettingsDialog on Python 3.7 with the following error message:
```
asctime: 01/17/2020 03:42:52 AM
levelname: CRITICAL
name: DownloaderForReddit.__main__
message: Unhandled exception
exc_info: AttributeError: __getattribute__
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "E:\Repos\DownloaderForReddit\repo\DownloaderForReddit\GUI\DownloaderForRedditGUI.py", line 246, in <lambda>
user_settings.triggered.connect(lambda: self.user_settings(0, False))
File "E:\Repos\DownloaderForReddit\repo\DownloaderForReddit\GUI\DownloaderForRedditGUI.py", line 342, in user_settings
self.running)
File "E:\Repos\DownloaderForReddit\repo\DownloaderForReddit\GUI\RedditObjectSettings …
```
=> Updated PyQt Version

DownloaderForReddit/Core/Content.py, DownloaderForReddit/Extractors/RedditVideoExtractor.py, DownloaderForReddit/Utils/VideoMerger.py, Tests/UnitTests/Extractors/test_DirectExtractor.py, Tests/UnitTests/Extractors/test_GfycatExtractor.py, Tests/UnitTests/Extractors/test_ImgurExtractor.py, Tests/UnitTests/Extractors/test_RedditVideoExtractor.py, Tests/UnitTests/Extractors/test_VidbleExtractor.py
Fixes files of all types from being overwritten when a file with the same name is downloaded.  The new files will now be fixed with an incrementing number to avoid duplicate names.
Also fixes the final part of issue #94 in which reddit video files with duplicate names were either overwriting the existing file or not merging.
=> Duplicate file name fix

DownloaderForReddit/Core/Content.py, DownloaderForReddit/Core/DownloadRunner.py, DownloaderForReddit/Extractors/BaseExtractor.py, DownloaderForReddit/Utils/Injector.py, DownloaderForReddit/Utils/SystemUtil.py, Tests/UnitTests/Core/test_Content.py
The new content naming scheme, which was implemented to rename files with duplicate names instead of overwriting them, created a problem when trying to open the last download dialog in which the application would crash.  This PR fixes this issue.
=> Last downloaded fix

DownloaderForReddit/Utils/VideoMerger.py
FFMPEG console no longer pops up. Instead, output is piped to DFR console This resolves Issue #109
=> Hid FFMPEG console 

DownloaderForReddit/GUI/FailedDownloadsDialog.py
The detail table wasn't updating if the selection was changed via keyboard.
=> Fixed FailedDownloadsDialog selection

DownloaderForReddit/Extractors/GfycatExtractor.py, Tests/UnitTests/Extractors/test_GfycatExtractor.py
Due to the GfyCat/Redgifs split, some gfycat links are now being serviced by redgifs instead. 
To account for this, the GfycatExtractor now queries the redgifs API before failing a gfycat link.
=> Added fallback to redgifs

DownloaderForReddit/Core/Content.py, DownloaderForReddit/Core/UpdaterChecker.py, DownloaderForReddit/Extractors/BaseExtractor.py, DownloaderForReddit/Extractors/GfycatExtractor.py, DownloaderForReddit/Utils/ImgurUtils.py, Tests/UnitTests/Extractors/test_GfycatExtractor.py, Tests/UnitTests/Utils/test_ImgurUtils.py
For many reasons, http requests may hang. I'll just defer to the official docs:
> Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely
https://2.python-requests.org/en/master/user/quickstart/#timeouts
I was finding that DownloaderForReddit would sometimes hang forever. Adding this timeout fixed it and downloads were correctly recognized as failed.
=> fix: add a timeout to abort hanging requests

DownloaderForReddit/extractors/gfycat_extractor.py, Tests/unittests/extractors/test_gfycat_extractor.py
Partially fixes Issue #141 
Looks like the problem was twofold: 
* The extractor failed to recognize Redgifs urls that start with `www.`
* It failed to properly extract the gif_id in the case of urls with `/watch/[gif_id]`
For some reason, the redgifs will occasionally time out. 
```
HTTPSConnectionPool(host='api.redgifs.com', port=443): Read timed out. (read timeout=10)
```
=> Redgifs fix

DownloaderForReddit/gui/settings/schedule_settings_widget.py, DownloaderForReddit/scheduling/scheduler.py, DownloaderForReddit/scheduling/tasks.py
Fix #276.  
The scheduler allowed a WEEK time interval, which is not supported.  This fixes this issue and adds better error handling to the scheduler.
=> Scheduling fix

.github/workflows/Build.yml
The Version 3.14 release failed to create because 3fe8ee3d2c11e8b9d54fe643549d52ac365f51e2 was pushed with 420f38eb06a77e395a8bb3a552874d30ea72823b. This PR fixes the workflow so that this doesn't happen in the future. 
Note: The release for 3.14 will have to be manually triggered. The easiest way is as follows: 
1. Create a branch called `release_test` at commit 3fe8ee3d2c11e8b9d54fe643549d52ac365f51e2.
2. Push the branch to the repo. 
3. Once the release has been created, you can delete the `release_test` branch.
=> Fixed release not being made when multiple commits pushed

DownloaderForReddit/persistence/settings_manager.py
Fix an encoding error that was sometimes possible when saving and or loading the config file.
=> Fix config file encoding on load and save

DownloaderForReddit/core/download_runner.py
Fix a database query error that prevented posts and content without an error from being pulled from the database when attempting to re-run failed downloads/extractions.
=> Fix content and posts with no errors not being retried

DownloaderForReddit/core/download/__init__.py, DownloaderForReddit/core/download/downloader.py, DownloaderForReddit/core/download/multipart_downloader.py, DownloaderForReddit/core/download_runner.py, DownloaderForReddit/core/update_runner.py, DownloaderForReddit/extractors/redgifs_extractor.py
The multi-part downloader was not performing correctly with the addition of making download requests with required headers.  This fix makes the multi-part downloader pull from the same header library that the main downloader now uses.
=> Fix multi-part downloader

DownloaderForReddit/scheduling/scheduler.py, DownloaderForReddit/scheduling/tasks.py
Fix #323 
Scheduled download tasks stored in the database were using the same UUID number instead of generating new ones.  This was causing a crash when trying to add more than one task because of the unique constraint on that database column.
=> Fix download scheduler not storing multiple download tasks

DownloaderForReddit/core/const.py, DownloaderForReddit/core/download_runner.py, DownloaderForReddit/customwidgets/link_cursor_handler.py, DownloaderForReddit/gui/downloader_for_reddit_gui.py, DownloaderForReddit/utils/html_formatting.py, DownloaderForReddit/utils/reddit_utils.py, DownloaderForReddit/viewmodels/hyperlink_delegate.py, DownloaderForReddit/viewmodels/output_view_model.py, Tests/unittests/utils/test_html_formatting.py, Tests/unittests/viewmodels/test_hyperlink_delegate.py
Reddit's rate limiting has been a consistent issue since they were introduced, but it has been unclear to the user what issues are related to the rate limit.  The rate limits were (mostly) already caught and handled as part of the larger error handling scheme, but they were not handled individually and were not reported to the user in a meaningful way.  
This pull request fixes this lack of reporting and as a side effect of these fixes, adds new URL handling abilities in the output window.
=> Improved rate limit handling

DownloaderForReddit/viewmodels/reddit_object_list_model.py
Fix bug where the number of rows falls out of sync with the number of reddit objects in the GUI list when searching. 
https://github.com/user-attachments/assets/f31c3552-9b66-49b9-bc5b-e7fd46d66a0f
https://github.com/user-attachments/assets/c91cc049-6dd5-44c3-9bd0-97aa88ef7852
Test Build: https://github.com/zacker150/DownloaderForReddit/actions/runs/16854095313
=> Fix row count not updating on search
